name: 步步宝

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 0-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bububao
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【步步宝】'
        run: |
          node Task/bububao.js
        env:
          BBB_bububaoTOKEN: ${{ secrets. BBB_bububaoTOKEN }}
          BBB_CASH: ${{ secrets. BBB_CASH }}

